[package]
authors = ["Kevin King <kevin@krypt.co>"]
name = "pkcs11shim"
version = "0.1.0"

[dependencies]
lazy_static = "*"
libc = "*"
syslog = "*"
users = "0.5.0"

[lib]
crate-type = ["cdylib"]
name = "krpkcs11"
